"""Daily auto-scan + email alert.

Env vars:
  EMAIL_USER       Gmail address (ผู้ส่ง)
  EMAIL_PASSWORD   Gmail App Password 16 ตัว
  EMAIL_TO         อีเมลผู้รับ
Optional:
  UNIVERSE         "sp500" (default) | "nasdaq100" | "dow30" | "ticker1,ticker2,..."
  STRATEGY         "fresh_breakout" (default) | "near_52w_high"
"""
import os
import smtplib
from datetime import datetime
from email.message import EmailMessage

import yfinance as yf
import pandas as pd

from presets import get_sp500, NASDAQ_100, DOW_30
from strategies import STRATEGIES


def fetch_many(tickers: tuple[str, ...]) -> dict[str, pd.DataFrame]:
    if not tickers:
        return {}
    data = yf.download(
        list(tickers), period="2y", interval="1d",
        progress=False, auto_adjust=False, group_by="ticker", threads=True,
    )
    out: dict[str, pd.DataFrame] = {}
    if len(tickers) == 1:
        t = tickers[0]
        if isinstance(data.columns, pd.MultiIndex):
            data.columns = data.columns.get_level_values(0)
        out[t] = data
    else:
        for t in tickers:
            try:
                df = data[t].dropna(how="all")
                if not df.empty:
                    out[t] = df
            except KeyError:
                pass
    return out


def get_universe() -> tuple[str, list[str]]:
    spec = os.environ.get("UNIVERSE", "sp500").strip()
    if spec.lower() == "sp500":
        return "S&P 500", get_sp500()
    if spec.lower() == "nasdaq100":
        return "Nasdaq 100", NASDAQ_100
    if spec.lower() == "dow30":
        return "Dow 30", DOW_30
    if "," in spec:
        return "Custom", [t.strip().upper() for t in spec.split(",") if t.strip()]
    return "S&P 500", get_sp500()


def render_html(buys, hold, sell, nodata, universe_name, strategy) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    headers = strategy["headers"]
    head_html = "".join(f'<th style="border:1px solid #ddd;padding:8px">{h}</th>' for h in headers)

    if buys:
        rows = "".join(strategy["html_row"](b["ticker"], b["metrics"]) for b in buys)
        table = f"""
        <table cellpadding="0" cellspacing="0" style="border-collapse:collapse;font-family:sans-serif;border:1px solid #ddd;margin-top:10px">
          <thead style="background:#16a34a;color:white"><tr>{head_html}</tr></thead>
          <tbody style="background:white">{rows}</tbody>
        </table>
        """
    else:
        table = "<p style='color:#666'>วันนี้ไม่พบหุ้นที่เข้าเงื่อนไข BUY ครบทุกข้อ</p>"

    return f"""<!DOCTYPE html><html><body style="font-family:Arial,sans-serif;max-width:800px">
  <h2 style="color:#1f2937">🚀 Stock Breakout Scan — {now}</h2>
  <p>
    <b>Universe:</b> {universe_name} ({len(buys)+hold+sell+nodata} tickers) &nbsp;|&nbsp;
    <b>Strategy:</b> {strategy['label']}
  </p>
  <p style="color:#666;font-size:13px"><i>{strategy['description']}</i></p>
  <p style="font-size:16px">
    🟢 BUY: <b style="color:#16a34a">{len(buys)}</b> &nbsp;|&nbsp;
    🟡 HOLD: {hold} &nbsp;|&nbsp;
    🔴 SELL: {sell} &nbsp;|&nbsp;
    ⚪ NO DATA: {nodata}
  </p>
  {table}
  <hr style="margin-top:24px;border:none;border-top:1px solid #ddd">
  <p style="color:#888;font-size:12px">
    Auto-generated by Stock Breakout Scanner<br>
    {strategy['description']}
  </p>
</body></html>"""


def send_email(html: str, subject: str):
    user = os.environ["EMAIL_USER"]
    password = os.environ["EMAIL_PASSWORD"]
    to = os.environ["EMAIL_TO"]

    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = user
    msg["To"] = to
    msg.set_content("View this email in HTML-capable client.")
    msg.add_alternative(html, subtype="html")

    with smtplib.SMTP("smtp.gmail.com", 587) as smtp:
        smtp.starttls()
        smtp.login(user, password)
        smtp.send_message(msg)


def main():
    # Strategy selection
    strategy_key = os.environ.get("STRATEGY", "fresh_breakout").lower()
    if strategy_key not in STRATEGIES:
        print(f"[warn] Unknown STRATEGY={strategy_key}, falling back to fresh_breakout")
        strategy_key = "fresh_breakout"
    strategy = STRATEGIES[strategy_key]
    analyze = strategy["analyze"]
    print(f"Strategy: {strategy['label']}")

    # Universe
    universe_name, universe = get_universe()
    print(f"Universe: {universe_name} ({len(universe)} tickers)")

    print("Downloading data...")
    data = fetch_many(tuple(universe))
    print(f"Got data for {len(data)} tickers")

    buys, hold, sell, nodata = [], 0, 0, 0
    for t in universe:
        df = data.get(t)
        if df is None or df.empty:
            nodata += 1
            continue
        r = analyze(df)
        if r is None:
            nodata += 1
            continue
        if r["signal"] == "BUY":
            buys.append({"ticker": t, **r})
        elif r["signal"] == "HOLD/WAIT":
            hold += 1
        else:
            sell += 1

    # เรียง BUY ตาม close/pivot (สดที่สุดอยู่บน) สำหรับ fresh_breakout
    # หรือ % from 52W H (ใกล้สุดอยู่บน) สำหรับ near_52w_high
    if strategy_key == "fresh_breakout":
        buys.sort(key=lambda b: b["metrics"]["pct_from_pivot"])  # น้อยสุด (สด)
    else:
        buys.sort(key=lambda b: b["metrics"]["pct_from_high52"], reverse=True)

    print(f"\nResults: BUY={len(buys)}  HOLD={hold}  SELL={sell}  NO DATA={nodata}")
    if buys:
        print("BUY tickers:", ", ".join(b["ticker"] for b in buys))

    html = render_html(buys, hold, sell, nodata, universe_name, strategy)
    subject = (f"🚀 [{strategy_key}] {len(buys)} BUY signal(s)" if buys
               else f"📊 [{strategy_key}] No BUY today")

    if all(os.environ.get(k) for k in ("EMAIL_USER", "EMAIL_PASSWORD", "EMAIL_TO")):
        send_email(html, subject)
        print(f"\n[OK] Sent email to {os.environ['EMAIL_TO']}")
    else:
        with open("last_scan.html", "w", encoding="utf-8") as f:
            f.write(html)
        print("\n[DRY RUN] EMAIL env vars not set - HTML saved to last_scan.html")


if __name__ == "__main__":
    main()
